server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5  #连接池大小
      min-idle: 10    #最小空闲连接数
      max-active: 20  #最大连接数
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
      poll-interval: 3000ms     # 解决项目自动重新编译后接口报404的问题
      quiet-period: 2999ms
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: secret #JWT加解密使用的密钥
  expiration: 8640000 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

